require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-thread_safety
  - rubocop-sequel
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - migrate/**/*
Layout/LineLength:
  Max: 120
Layout/LeadingCommentSpace:
  Exclude:
    - 'config.ru'
Layout/EndOfLine:
  EnforcedStyle: lf
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  IndentationWidth: 2
Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods
Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
Metrics/MethodLength:
  CountAsOne: ['array', 'heredoc', 'hash']
Style/Documentation:
  Enabled: false
