Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/**/*'

Style/Documentation:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/LeadingCommentSpace:
  Exclude:
    - 'config.ru'

AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - 'lib/ditty/rake_tasks.rb'
    - 'ditty.gemspec'
    - 'migrate/*'
