sudo: false
language: ruby
rvm:
  - 2.4.0
  - 2.3.3
  - 2.2.6
  - 2.1.10
  - 2.0.0
gemfile: Gemfile.ci
env:
  - DATABASE_URL="sqlite::memory:" RACK_ENV=test
before_install: gem install bundler -v 1.12.5
