sudo: false
language: ruby
rvm:
  - 2.4.0
  - 2.3.3
  - 2.2.6
gemfile: Gemfile.ci
env:
  - DATABASE_URL="sqlite::memory:" RACK_ENV=test
before_install: gem install bundler -v 1.12.5
addons:
  code_climate:
    repo_token: 289860573c6284a8e277de86848caba84d840be49e35f3601bcd672ab40d1e35
after_success:
  - bundle exec codeclimate-test-reporter
